SELECT COUNT(ID_BILLET)
FROM BILLET;

SELECT SUM(PRIX_FINAL)
FROM BILLET;

SELECT COUNT(ID_BILLET), SUM(PRIX_FINAL)
FROM BILLET
WHERE ID_EMPLACEMENT = ?2;

SELECT COUNT(ID_BILLET), SUM(PRIX_FINAL)
FROM BILLET
INNER JOIN MATCHSIMPLE /* MATCHDOUBLE */
WHERE BILLET.ID_MATCH_SIMPLE /* BILLET.ID_MATCH_DOUBLE */ = MATCHSIMPLE.ID_MATCH_SIMPLE /* MATCHDOUBLE.ID_MATCH_DOUBLE */
AND PHASE_TOURNOI = ?1
AND ID_EMPLACEMENT = ?2;

SELECT ID_MATCH_SIMPLE /* ID_MATCH_DOUBLE */
FROM MATCHSIMPLE /* MATCHDOUBLE */
WHERE PHASE_TOURNOI = ?1;

SELECT COUNT(ID_BILLET), SUM(PRIX_FINAL)
FROM BILLET
WHERE ID_MATCH_SIMPLE /* BILLET.ID_MATCH_DOUBLE */ = ?1;
AND ID_EMPLACEMENT = ?2;