SELECT ID_MATCH_SIMPLE, HORAIRE_SIMPLE, PHASE_TOURNOI_SIMPLE /* ID_MATCH_DOUBLE, HORAIRE_DOUBLE, PHASE_TOURNOI_DOUBLE */
FROM MATCHSIMPLE /* MATCHDOUBLE */
WHERE PHASE_TOURNOI_SIMPLE /* PHASE_TOURNOI_SIMPLE */ = ?1;

SELECT PRENOM_TENNISMAN, NOM_TENNISMAN
FROM TENNISMAN
INNER JOIN JOUE_SIMPLE
WHERE TENNISMAN.ID_TENNISMAN = JOUE_SIMPLE.ID_TENNISMAN
AND ID_MATCH_SIMPLE = ?1;

SELECT ID_EQUIPE
FROM JOUE_DOUBLE
WHERE ID_MATCH_DOUBLE = ?1;

SELECT PRENOM_TENNISMAN, NOM_TENNISMAN
FROM TENNISMAN
WHERE ID_EQUIPE = ?1;

SELECT NOM_TERRAIN
FROM TERRAIN
INNER JOIN MATCHSIMPLE /* MATCHDOUBLE */
WHERE TERRAIN.ID_TERRAIN = MATCHSIMPLE.ID_TERRAIN
AND ID_MATCH_SIMPLE = ?1;