SELECT ID_MATCH_SIMPLE /* ID_MATCH_DOUBLE */, PRIX_DE_BASE
FROM MATCHSIMPLE /* MATCHDOUBLE */
WHERE ID_MATCH_SIMPLE /* ID_MATCH_DOUBLE */ = ?1;

SELECT SURCOUT
FROM EMPLACEMENT
WHERE ID_EMPLACEMENT = ?1;

SELECT CODE
FROM CODEPROMO
WHERE CODE = ?1;